# Guards on the bundled demo datasets. These are generated by
# data-raw/bundle-demo.R; the assertions here pin invariants that the
# generation script must preserve so examples, vignettes, and byte
# snapshots stay stable.

test_that("bundled summary datasets carry arms in canonical dose order (#arm-order)", {
  # placebo, then dose-ascending, then Total. cdisc_saf_demo and
  # cdisc_saf_ae once shipped with Total first / drug_50 last because
  # they lacked the explicit reorder the other datasets apply.
  canonical <- c("placebo", "drug_50", "drug_100", "Total")
  dsets <- list(
    cdisc_saf_demo = cdisc_saf_demo,
    cdisc_saf_ae = cdisc_saf_ae,
    cdisc_saf_aesocpt = cdisc_saf_aesocpt,
    cdisc_saf_vital = cdisc_saf_vital,
    cdisc_eff_resp = cdisc_eff_resp
  )
  for (nm in names(dsets)) {
    nms <- names(dsets[[nm]])
    # Arm columns, in the order they appear in the data frame.
    as_stored <- nms[nms %in% canonical]
    # The same set, forced into canonical order.
    as_canonical <- canonical[canonical %in% nms]
    expect_identical(as_stored, as_canonical, info = nm)
  }
})
